[project]
name = "log_reader"
version = "0.1.0"
description = "Log reader GUI"
dependencies = []

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["log_reader"]