# -*- coding: utf-8 -*-
import sys

################################################################################
## Form generated from reading UI file 'gui_project.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDateEdit, QLabel, QLineEdit,
    QListWidget, QListWidgetItem, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QToolButton,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1100, 625)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1100, 625))
        MainWindow.setMaximumSize(QSize(1100, 625))
        font = QFont()
        font.setFamilies([u"Arial"])
        MainWindow.setFont(font)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        font1 = QFont()
        font1.setFamilies([u"Segoe UI"])
        font1.setPointSize(9)
        font1.setBold(True)
        self.centralwidget.setFont(font1)
        self.file_path_box = QLineEdit(self.centralwidget)
        self.file_path_box.setObjectName(u"file_path_box")
        self.file_path_box.setGeometry(QRect(40, 30, 501, 31))
        font2 = QFont()
        font2.setBold(False)
        self.file_path_box.setFont(font2)
        self.file_path_box.setFocusPolicy(Qt.StrongFocus)
        self.log_list = QListWidget(self.centralwidget)
        self.log_list.setObjectName(u"log_list")
        self.log_list.setGeometry(QRect(40, 120, 541, 401))
        self.log_list.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.next_log = QPushButton(self.centralwidget)
        self.next_log.setObjectName(u"next_log")
        self.next_log.setGeometry(QRect(490, 540, 93, 28))
        font3 = QFont()
        font3.setFamilies([u"Calibri"])
        font3.setPointSize(9)
        font3.setBold(True)
        self.next_log.setFont(font3)
        self.next_log.setFocusPolicy(Qt.NoFocus)
        self.previous_log = QPushButton(self.centralwidget)
        self.previous_log.setObjectName(u"previous_log")
        self.previous_log.setGeometry(QRect(370, 540, 93, 28))
        self.previous_log.setFont(font3)
        self.select_file = QToolButton(self.centralwidget)
        self.select_file.setObjectName(u"select_file")
        self.select_file.setGeometry(QRect(550, 30, 31, 31))
        self.lower_bound_date = QDateEdit(self.centralwidget)
        self.lower_bound_date.setObjectName(u"lower_bound_date")
        self.lower_bound_date.setGeometry(QRect(110, 81, 121, 21))
        self.lower_bound_date.setFont(font2)
        self.lower_bound_date.setCalendarPopup(True)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(54, 80, 51, 20))
        font4 = QFont()
        font4.setFamilies([u"Calibri"])
        font4.setPointSize(11)
        font4.setBold(True)
        self.label.setFont(font4)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(260, 80, 41, 20))
        self.label_2.setFont(font4)
        self.upper_bound_box = QDateEdit(self.centralwidget)
        self.upper_bound_box.setObjectName(u"upper_bound_box")
        self.upper_bound_box.setGeometry(QRect(300, 80, 121, 21))
        self.upper_bound_box.setFont(font2)
        self.upper_bound_box.setCalendarPopup(True)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(630, 120, 101, 16))
        self.label_3.setFont(font4)
        self.remote_host_box = QLineEdit(self.centralwidget)
        self.remote_host_box.setObjectName(u"remote_host_box")
        self.remote_host_box.setGeometry(QRect(630, 140, 201, 31))
        font5 = QFont()
        font5.setBold(True)
        self.remote_host_box.setFont(font5)
        self.remote_host_box.setReadOnly(True)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(630, 190, 55, 16))
        self.label_4.setFont(font4)
        self.date_box = QLineEdit(self.centralwidget)
        self.date_box.setObjectName(u"date_box")
        self.date_box.setGeometry(QRect(630, 210, 141, 31))
        self.date_box.setFont(font5)
        self.date_box.setReadOnly(True)
        self.time_box = QLineEdit(self.centralwidget)
        self.time_box.setObjectName(u"time_box")
        self.time_box.setGeometry(QRect(790, 210, 121, 31))
        self.time_box.setFont(font5)
        self.time_box.setReadOnly(True)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(790, 190, 55, 16))
        self.label_5.setFont(font4)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(930, 190, 81, 16))
        self.label_6.setFont(font4)
        self.timezone_box = QLineEdit(self.centralwidget)
        self.timezone_box.setObjectName(u"timezone_box")
        self.timezone_box.setGeometry(QRect(930, 210, 131, 31))
        self.timezone_box.setFont(font5)
        self.timezone_box.setReadOnly(True)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(630, 260, 101, 16))
        self.label_7.setFont(font4)
        self.status_color = QWidget(self.centralwidget)
        self.status_color.setObjectName(u"status_color")
        self.status_color.setGeometry(QRect(630, 280, 151, 31))
        self.status_color.setStyleSheet(u"background-color: ;")
        self.status_box = QLineEdit(self.centralwidget)
        self.status_box.setObjectName(u"status_box")
        self.status_box.setGeometry(QRect(630, 280, 113, 31))
        font6 = QFont()
        font6.setFamilies([u"Calibri"])
        font6.setBold(True)
        self.status_box.setFont(font6)
        self.status_box.setReadOnly(True)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(630, 330, 61, 16))
        self.label_8.setFont(font4)
        self.method_box = QLineEdit(self.centralwidget)
        self.method_box.setObjectName(u"method_box")
        self.method_box.setGeometry(QRect(630, 350, 113, 31))
        self.method_box.setFont(font6)
        self.method_box.setReadOnly(True)
        self.code_info = QToolButton(self.centralwidget)
        self.code_info.setObjectName(u"code_info")
        self.code_info.setGeometry(QRect(800, 280, 31, 31))
        font7 = QFont()
        font7.setPointSize(9)
        font7.setBold(True)
        self.code_info.setFont(font7)
        self.code_info.setStyleSheet(u"QToolButton {\n"
"border-radius: 15px; \n"
"font-weight: bold;\n"
"background-color: #7f8c8d;\n"
"border: 1px solid #606060;\n"
"color: white;\n"
"}\n"
"QToolButton:hover {\n"
"background-color: #606060; \n"
"}")
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(630, 400, 81, 16))
        self.resource_box = QLineEdit(self.centralwidget)
        self.resource_box.setObjectName(u"resource_box")
        self.resource_box.setGeometry(QRect(630, 420, 431, 31))
        self.resource_box.setReadOnly(True)
        self.size_box = QLineEdit(self.centralwidget)
        self.size_box.setObjectName(u"size_box")
        self.size_box.setGeometry(QRect(630, 491, 113, 31))
        self.size_box.setReadOnly(True)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(630, 470, 55, 16))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1100, 26))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.file_path_box.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter a path to the log file", None))
        self.next_log.setText(QCoreApplication.translate("MainWindow", u"Next", None))
        self.previous_log.setText(QCoreApplication.translate("MainWindow", u"Previous", None))
        self.select_file.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"From", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"To", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Remote Host", None))
        self.remote_host_box.setText("")
        self.remote_host_box.setPlaceholderText(QCoreApplication.translate("MainWindow", u"None", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Date", None))
        self.date_box.setPlaceholderText(QCoreApplication.translate("MainWindow", u"None", None))
        self.time_box.setPlaceholderText(QCoreApplication.translate("MainWindow", u"None", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Time", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Timezone", None))
        self.timezone_box.setPlaceholderText(QCoreApplication.translate("MainWindow", u"None", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Status Code", None))
        self.status_box.setPlaceholderText(QCoreApplication.translate("MainWindow", u"None", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Method", None))
        self.method_box.setPlaceholderText(QCoreApplication.translate("MainWindow", u"None", None))
        self.code_info.setText(QCoreApplication.translate("MainWindow", u"?", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Resource", None))
        self.resource_box.setPlaceholderText(QCoreApplication.translate("MainWindow", u"None", None))
        self.size_box.setPlaceholderText(QCoreApplication.translate("MainWindow", u"None", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Size", None))
    # retranslateUi

if __name__ == "__main__":
    app = QApplication(sys.argv)

    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)  # <-- pass the QMainWindow instance here
    MainWindow.show()

    sys.exit(app.exec())